// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/translate-editor/TranslateEditor.tsx": () => import("../components/mockups/translate-editor/TranslateEditor.tsx")
};
